ARG image_name
FROM $image_name
ARG IMAGE_NAME
USER root
COPY docker/scripts/entrypoint-test.sh /entrypoint-test.sh
RUN pip install pytest pytest-watch pytest-env flake8
USER airflow
ENTRYPOINT ["/entrypoint-test.sh"]
