#!/bin/bash
# Tag the the built test image for reuse
# Pieced together undocumented docker cloud build behavior from:
#     https://github.com/andyneff/highland_builder/blob/master/builder.py

BUILT_TEST_IMAGE=${BUILD_CODE}_sut
CACHE_REPO=$DOCKER_REPO:$CACHE_TAG
CACHED_TEST_IMAGE=${CACHE_REPO}-test

echo 'Tagging to ' $CACHED_TEST_IMAGE
docker tag $BUILT_TEST_IMAGE $CACHED_TEST_IMAGE
docker push $CACHED_TEST_IMAGE
