#[2018-04-24 16:59:46,061] {__init__.py:57} INFO - Using executor SequentialExecutor
#[2018-04-24 16:59:46,257] {driver.py:120} INFO - Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
#[2018-04-24 16:59:46,287] {driver.py:120} INFO - Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
docker run -it --rm -v /usr/people/agataf/.cloudvolume/secrets:/root/.cloudvolume/secrets seunglab/synaptor chunk_ccs gs://neuroglancer/agataf/golden/mito_inference gs://neuroglancer/agataf/golden/objects2 gs://neuroglancer/agataf/golden/proc_dir2 0.19 400 --chunk_begin 0 0 0 --chunk_end 512 512 256 --mip 1
docker run -it --rm -v /usr/people/agataf/.cloudvolume/secrets:/root/.cloudvolume/secrets seunglab/synaptor chunk_ccs gs://neuroglancer/agataf/golden/mito_inference gs://neuroglancer/agataf/golden/objects2 gs://neuroglancer/agataf/golden/proc_dir2 0.19 400 --chunk_begin 0 512 0 --chunk_end 512 1024 256 --mip 1
docker run -it --rm -v /usr/people/agataf/.cloudvolume/secrets:/root/.cloudvolume/secrets seunglab/synaptor chunk_ccs gs://neuroglancer/agataf/golden/mito_inference gs://neuroglancer/agataf/golden/objects2 gs://neuroglancer/agataf/golden/proc_dir2 0.19 400 --chunk_begin 512 0 0 --chunk_end 1024 512 256 --mip 1
docker run -it --rm -v /usr/people/agataf/.cloudvolume/secrets:/root/.cloudvolume/secrets seunglab/synaptor chunk_ccs gs://neuroglancer/agataf/golden/mito_inference gs://neuroglancer/agataf/golden/objects2 gs://neuroglancer/agataf/golden/proc_dir2 0.19 400 --chunk_begin 512 512 0 --chunk_end 1024 1024 256 --mip 1
docker run -it --rm -v /usr/people/agataf/.cloudvolume/secrets:/root/.cloudvolume/secrets seunglab/synaptor merge_ccs gs://neuroglancer/agataf/golden/proc_dir2 400
docker run -it --rm -v /usr/people/agataf/.cloudvolume/secrets:/root/.cloudvolume/secrets seunglab/synaptor remap_ids gs://neuroglancer/agataf/golden/objects2 gs://neuroglancer/agataf/golden/objects2 gs://neuroglancer/agataf/golden/proc_dir2 --chunk_begin 0 0 0 --chunk_end 512 512 256 --mip 1
docker run -it --rm -v /usr/people/agataf/.cloudvolume/secrets:/root/.cloudvolume/secrets seunglab/synaptor remap_ids gs://neuroglancer/agataf/golden/objects2 gs://neuroglancer/agataf/golden/objects2 gs://neuroglancer/agataf/golden/proc_dir2 --chunk_begin 0 512 0 --chunk_end 512 1024 256 --mip 1
docker run -it --rm -v /usr/people/agataf/.cloudvolume/secrets:/root/.cloudvolume/secrets seunglab/synaptor remap_ids gs://neuroglancer/agataf/golden/objects2 gs://neuroglancer/agataf/golden/objects2 gs://neuroglancer/agataf/golden/proc_dir2 --chunk_begin 512 0 0 --chunk_end 1024 512 256 --mip 1
docker run -it --rm -v /usr/people/agataf/.cloudvolume/secrets:/root/.cloudvolume/secrets seunglab/synaptor remap_ids gs://neuroglancer/agataf/golden/objects2 gs://neuroglancer/agataf/golden/objects2 gs://neuroglancer/agataf/golden/proc_dir2 --chunk_begin 512 512 0 --chunk_end 1024 1024 256 --mip 1
docker run -it --rm -v /usr/people/agataf/.cloudvolume/secrets:/root/.cloudvolume/secrets seunglab/synaptor chunk_overlaps gs://neuroglancer/agataf/golden/objects2 gs://neuroglancer/golden_v0/segmentation gs://neuroglancer/agataf/golden/proc_dir2 --chunk_begin 0 0 0 --chunk_end 512 512 256 --mip 1
docker run -it --rm -v /usr/people/agataf/.cloudvolume/secrets:/root/.cloudvolume/secrets seunglab/synaptor chunk_overlaps gs://neuroglancer/agataf/golden/objects2 gs://neuroglancer/golden_v0/segmentation gs://neuroglancer/agataf/golden/proc_dir2 --chunk_begin 0 512 0 --chunk_end 512 1024 256 --mip 1
docker run -it --rm -v /usr/people/agataf/.cloudvolume/secrets:/root/.cloudvolume/secrets seunglab/synaptor chunk_overlaps gs://neuroglancer/agataf/golden/objects2 gs://neuroglancer/golden_v0/segmentation gs://neuroglancer/agataf/golden/proc_dir2 --chunk_begin 512 0 0 --chunk_end 1024 512 256 --mip 1
docker run -it --rm -v /usr/people/agataf/.cloudvolume/secrets:/root/.cloudvolume/secrets seunglab/synaptor chunk_overlaps gs://neuroglancer/agataf/golden/objects2 gs://neuroglancer/golden_v0/segmentation gs://neuroglancer/agataf/golden/proc_dir2 --chunk_begin 512 512 0 --chunk_end 1024 1024 256 --mip 1
docker run -it --rm -v /usr/people/agataf/.cloudvolume/secrets:/root/.cloudvolume/secrets seunglab/synaptor merge_overlaps gs://neuroglancer/agataf/golden/proc_dir2 
